[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
strict_optional = True
warn_redundant_casts = True
warn_no_return = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings.base

[mypy-*.migrations.*]
ignore_errors = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-gdal.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True
